name: hello-world

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: say hello world
        uses: ./.github/actions/hello-world
  hello-mayya-job:
    needs: [hello-world-job]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Mayya"
        name: say hello Mayya



