name: pull_request

on: [pull_request]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.4'

      - name: install deps
        run: yarn install

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: build
        run: yarn build
