name: release

on:
  release:
    types: [published]

env:
  GCP_REGISTRY: europe-west3-docker.pkg.dev
  GCP_PROJECT_ID: simple-326714
  APP_NAME: next-app
  VERSION: ${{ github.events.release.tag_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "${{ toJson(github) }}"

      - uses: actions/checkout@v2

      - name: build docker image
        run: docker build --tag ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/docker/${{ env.APP_NAME }}:${{ env.VERSION }} .
      
      - name: push docker image
        run: docker push ${{ env.GCP_REGISTRY }}/${{ env.GCP_PROJECT_ID }}/docker/${{ env.APP_NAME }}:${{ env.VERSION }}
        